---
- name: Add servers to DiscordGSM
  hosts: discordgsm
  gather_facts: no
  
  vars:
    discordgsm_db: "/path/to/servers.db"
    servers:
      - guild_id: 123456789
        channel_id: 987654321
        game_id: "minecraft"
        address: "mc.example.com"
        query_port: 25565
      # Add more servers as needed

  tasks:
    - name: Add server to DiscordGSM
      command: >
        python3 add_server.py
        --guild_id {{ item.guild_id }}
        --channel_id {{ item.channel_id }}
        --game_id {{ item.game_id }}
        --address {{ item.address }}
        --query_port {{ item.query_port }}
        --db_path {{ discordgsm_db }}
      register: result
      failed_when: result.rc != 0
      with_items: "{{ servers }}"